rules:
  - description: Discovery sensitive files expousure
    method: GET
    wordlist: ./wordlists/generic/juicefiles.txt
    return: 200
    length: "> 0"
  - description: Find valid paths
    method: GET
    wordlist: ./wordlists/default.txt
    exclude: 404,204,410,302,405,429
    length: "> 0"