rules:
  - description: Find valid paths
    method: GET
    wordlist: wordlists/default.txt
    exclude: 404,204,410
  - description: Discovery sensitive files expousure
    method: GET
    wordlist: wordlists/juicefiles.txt
    return: 200,204