name: secureperl
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Audit code
      run:
        sudo apt install -y libpath-iterator-rule-perl libtest-perl-critic-perl
        curl -s https://raw.githubusercontent.com/htrgouvea/secureperl/main/secureperl.pl | perl
