name: Testing on Ubuntu
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt install -y perl cpanminus
        sudo cpanm --installdeps .
    - name: Verify the basic usage
      run: |
        perl nozaki.pl --help
