name: ZARN

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '28 23 * * 1'
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        git clone https://github.com/htrgouvea/zarn
        sudo apt install -y perl cpanminus
        cd zarn && sudo cpanm --installdeps .
    - name: Hunt for findings
      run: |
        cd zarn && perl zarn.pl --source ../ --sarif ../zarn.sarif
    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: zarn.sarif