name: ZARN SAST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '28 23 * * 1'

jobs:
  zarn:
    name: Security Static Analaysis with ZARN
    runs-on: ubuntu-20.04
    steps:
    - uses: htrgouvea/zarn@0.1.0
